name: Rebase

on: [issue_comment]

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
